### ISSUE TITLE
Problema con Los input[type="number"]

### ISSUE THREAD

**Issue by tipoxd** [ivanosquis10/bolivarium-conversor#1]
Buenos dias ha continuacion en pequeño detalle que le vi.

en la parte de 
![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/b19cc454-7df9-4e0f-885b-f4cdec278fec)
en los inputs no se puede eliminar el numero 0 que trae por defecto

es un poco tedioso el uso porque debe ingresar un numero primero y luego eliminar el 0

(claro si seleccionas todo el input y ingresar algun numero alli se cambia de una , pero hay personas que no saben eso).

en modo telefono lo mismo debes hasta tener que mover el foco donde vas a escribir para poder quitar el 0.

### **Solucion (mi opinion):**

**permite que el input pueda estar vacio y luego validar en codigo si esta vacio mandar una alerta algo, del resto que permita que los inputs esten asi.

del resto la app esta muy Chevere.**

**Comment by ivanosquis10** [comment]
Genial, le echaré un vistazo. Gracias amigo❤️
