### ISSUE TITLE
Problema de consulta de la api

### ISSUE THREAD

**Issue by tipoxd** [ivanosquis10/bolivarium-conversor#13]
la pagina tiene un detalle, cuando el dolar actualiza, en la pagina dura un rato es cargar la nueva info

ejemplo ahorita

![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/eae20d69-a63a-46b3-b24c-6480d78759d6)

esto muestra la api
![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/994206d1-65ef-4f1c-b63c-734283cb6b2b)

este es el precio del dolar actual

![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/1e39609a-b397-4203-87f6-184886b133b2)

y la pagina sigue marcando el monto anterior

![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/60485504-3660-4408-8a70-fe4580185277)

imagino que es un detalle de la pagina porque la api carga el monto.

lindo dia.

**Comment by ivanosquis10** [comment]
Si amigo, es un detalle según leí de con una opción de nextjs que no revalida la información a veces, entonces hay que actualizar la página, estoy pensando que puedo hacer para resolver esa cuestión :(
