### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by tipoxd** [ivanosquis10/bolivarium-conversor#3]
Opino que deberian agregar una parte de historial de conversion,
que te diga la fecha la hora  y que monto a que tasa hiciste el cambio.
y el resultado.

se guardaria en el localstorage.

[caso]
asi cuando quieras volver y decir ,cuanto fue que fue el monto que me dio hace rato, no debas volver a escribir el monto de la conversion para luego copiar el monto para X cosa.

(fue lo que me paso hace rato.)

se hubiera tenido el historial
podria copiar la data de otras veces que la utilize.
 
agilizará muchas mas el uso de la app.

**Comment by ivanosquis10** [comment]
Heeey, vale, me parece una idea interesante de desarrollar. Gracias amigo! No cierres el issue pls, para tenerlo presente y no se me olvide jajajjaa
