### ISSUE TITLE
Problema de la App

### ISSUE THREAD

**Issue by tipoxd** [ivanosquis10/bolivarium-conversor#42]
Buenos dias.

al momento de ingresar a la pagina se queda cargando:
![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/bc8dad99-31ee-4fd6-b426-c4788e836f19)

y luego se queda  asi 
![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/5174ea9f-e487-4521-9d53-420ed20f6a6f)

**Comment by ivanosquis10** [comment]
Si amigo, era la API que estaba caída y no funcionaba correctamente y mandaba un error, ya se resolvió
