### ISSUE TITLE
Listado de Bancos no Disponible

### ISSUE THREAD

**Issue by tipoxd** [ivanosquis10/bolivarium-conversor#52]
![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/d430d425-693b-4231-9a58-628944b89117)

Imagino que es un problema de la api interna
![image](https://github.com/ivanosquis10/bolivarium-conversor/assets/19245713/b1d2605d-281d-4a17-a32a-6596a228a4b8)

esta asi desde el dia 17/03/2024

**Comment by ivanosquis10** [comment]
La api exploto creo, tocará hacer cambio este fin, gracias por avisar amigo! Tengo que buscar otra api entonces

**Comment by tipoxd** [comment]
> La api exploto creo, tocará hacer cambio este fin, gracias por avisar amigo! Tengo que buscar otra api entonces

El creador de la API que consume , cambio la forma en qué se solicita 

Puede ver la conversación aquí 

https://github.com/fcoagz/api-pydolarvenezuela/issues/3

Imagino que ahora se tendrá que crear un json  Con las monedas a  consultar , luego iterar entre cada uno y luego mostrarlas

**Comment by ivanosquis10** [comment]
Ostia, bueno. Tocará echarle un vistazo. Si quieres arreglar eso, abre el issue y haces el PR amigo. Si no bueno, el fin veo eso :(

**Comment by ivanosquis10** [comment]
gracias!!!!!!!
